import type { Metadata } from "next";
import "../config/globals.css";
import React from "react";
import { Gothic_A1 } from "next/font/google";
import { Theme } from "@/components/Theme";
import AutoRefresh from "./AutoRefresh";
import { Navbar } from "@/components/bars/Navbar";
import { Footer } from "@/components/bars/Footer";
import Providers from "@/components/bars/Progressbar";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import { Toaster } from "@/components/ui/toaster";
import { GoogleAdSense } from "@/components/gasnippit";
import XlLeftSidebar from "@/components/bars/xlLeftSidebar";
import TagList from "@/components/bars/TagList";

export const metadata: Metadata = {
  title: "PromleeBlog",
  description: "Generated by PROMLEE",
  icons: {
    icon: "/icons/android-chrome-512x512.png",
  },
  verification: {
    other: {
      "naver-site-verification": ["bb67a48298f9b889aa36d5fe90aad935be356e31"],
    },
  },
};
const noto = Gothic_A1({
  weight: ["100", "500", "900"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AutoRefresh>
      <html className={`${noto.className} `} suppressHydrationWarning>
        <body>
          <Theme>
            <Navbar />
            <XlLeftSidebar />
            <div
              className={
                "w-full scroll-smooth bg-background px-10 focus:scroll-smooth md:min-h-[100vh] md:w-5/6 xl:w-3/5"
              }
            >
              <Providers>{children}</Providers>
            </div>
            <TagList />
            <Footer />
          </Theme>
          <Toaster />
          <GoogleAnalytics
            gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS || ""}
          />
          <GoogleTagManager
            gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER || ""}
          />
        </body>
        <GoogleAdSense />
      </html>
    </AutoRefresh>
  );
}
