import type { Metadata } from "next";
import "../config/globals.css";
import React from "react";
import { Gothic_A1 } from "next/font/google";
import { Theme } from "@/components/Theme";
import AutoRefresh from "./AutoRefresh";
import { Navbar } from "@/components/bars/Navbar";
import { Footer } from "@/components/bars/Footer";
// import { Analytics } from "@vercel/analytics/react";
// import { SpeedInsights } from "@vercel/speed-insights/next";
import Providers from "@/components/bars/Progressbar";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import { Loading } from "@/components/Loading";

export const metadata: Metadata = {
  title: "PromleeBlog",
  description: "Generated by PROMLEE",
  icons: {
    icon: "/icons/android-chrome-512x512.png",
  },
  verification: {
    other: {
      "naver-site-verification": ["bb67a48298f9b889aa36d5fe90aad935be356e31"],
    },
  },
};
const noto = Gothic_A1({
  weight: ["100", "500", "900"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AutoRefresh>
      <html className={`${noto.className} `} suppressHydrationWarning>
        <body>
          <Theme>
            <Suspense fallback={<Loading />}>
              <Navbar />
            </Suspense>
            <div
              className={
                "min-h-[100vh] w-full scroll-smooth bg-background px-10 focus:scroll-auto md:w-5/6 xl:w-3/5"
              }
            >
              <Providers>
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </Providers>
            </div>
            <Suspense fallback={<Loading />}>
              <Footer />
            </Suspense>
          </Theme>
          <Toaster />
          <Suspense fallback={<Loading />}>
            {/* <SpeedInsights />
            <Analytics /> */}
            <GoogleAnalytics
              gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS || ""}
            />
            <GoogleTagManager
              gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER || ""}
            />
          </Suspense>
        </body>
      </html>
    </AutoRefresh>
  );
}
