import type { Metadata } from "next";
import "../config/globals.css";
import React from "react";
import { Gothic_A1 } from "next/font/google";
import { Theme } from "@/components/Theme";
import AutoRefresh from "./AutoRefresh";
import { Navbar } from "@/components/bars/Navbar";
import { Footer } from "@/components/bars/Footer";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "PromleeBlog by Nextjs",
  description: "Generated by PROMLEE",
  icons: {
    icon: "/favicon.ico",
  },
};
const noto = Gothic_A1({
  weight: ["100", "500", "900"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AutoRefresh>
      <html className={`${noto.className} scroll-smooth focus:scroll-auto`}>
        <body>
          <Theme>
            <Navbar />
            <div
              className={
                "min-h-[800px] w-full scroll-smooth bg-background px-10 pb-40 md:w-5/6  xl:w-3/5"
              }
            >
              {children}
            </div>
            <Link href="#">
              <svg
                className="fixed right-4 top-14 h-6 w-6 rounded-full bg-foreground"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="none"
                viewBox="0 0 24 24"
              >
                <path
                  stroke="black"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="m5 15 7-7 7 7"
                />
              </svg>
            </Link>
            <Link href="#bottom">
              <svg
                className="fixed bottom-3 right-4 h-6 w-6 rounded-full bg-foreground"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="none"
                viewBox="0 0 24 24"
              >
                <path
                  stroke="black"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="m19 9-7 7-7-7"
                />
              </svg>
            </Link>
            <Footer />
          </Theme>
        </body>
      </html>
    </AutoRefresh>
  );
}
